// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gscmekwmxlwiwjkmpnti.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdzY21la3dteGx3aXdqa21wbnRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNDIzNzksImV4cCI6MjA2MDcxODM3OX0.heHL0MmZZi2wbEevpoFUL6d4TVCZNR47bpDLXwml7wQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: false
  }
});